name: server CI/CD

on:
  push:
    branches:
      - release
      - main
  pull_request:
    branches:
      - release
      - main

env:
  S3_BUCKET_NAME: dodo-buket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # application.properties 파일 생성
      # touch 파일 생성
      # echo "${{ secrets.PROPERTIES }}" >> ./application.properties ${{ secrets.PROPERTIES }}의 내용을 application.properties로 옮겨라
      - name: make application.yml
        run: |
          echo ">> mkdir & touch"
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo ">> copy application.yml"
          echo "${{ secrets.PROPERTIES }}" >> ./application.yml

      - name: make logback-spring.xml
        run: |
          echo ">> mkdir & touch"
          cd ./src/main/resources
          touch ./logback-spring.xml
          echo ">> copy logback-spring.xml"
          echo "${{ secrets.LOGBACK }}" >> ./logback-spring.xml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build --stacktrace > build.log
        shell: bash

      - name: Make zip file
        run: zip -r ./dodo.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./dodo.zip s3://$S3_BUCKET_NAME/

      - name: Code Deploy
        run:
          aws deploy create-deployment
          --application-name DODO-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name DODO-deploy
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=dodo.zip